### PR TITLE
add offline mode icon to navbar

### PR DESCRIPTION
**Pull request by jonmarcello**
Fixes: #530

**What** 
 - Added a offline mode icon to the top navbar

**Why**
 - Gives a visual indication to the user when they are using the app offline

**How**
 - Implemented `useOffline` which will return if the user is offline or not
 - Uses the `offline` and `online` eventListeners

**Testing**
 - Use the chrome debugger to set your network status to offline

**Screenshots**
 image

### CODE REVIEW

**Comment by karlolsonuc** [comment]
@jonmarcello you've some build errors to sort before this is ready for review, heads up.

**Review by karlolsonuc — CHANGES_REQUESTED** [review]
Gotta handle the build errors first: 
https://github.com/microsoft/community-organization-operations-suite/runs/6181301348?check_suite_focus=true

Excerpt from the build error:
`src/components/ui/OfflineModeNav/index.tsx(20,72): error TS2322: Type 'number' is not assignable to type 'string'.`

**Comment by jonmarcello** [comment]
> Gotta handle the build errors first: https://github.com/microsoft/community-organization-operations-suite/runs/6181301348?check_suite_focus=true
> 
> Excerpt from the build error: `src/components/ui/OfflineModeNav/index.tsx(20,72): error TS2322: Type 'number' is not assignable to type 'string'.`

Appologies, must have missed that.

It should be fine now

**Review by karlolsonuc — APPROVED** [review]
Looks solid to me. Approved.

**Pull request merged**
